plugins=(
        aliases
        asdf
        aws
        brew
        docker
        docker-compose
        docker-machine
        gcloud
        gh
	git
        git-flow
        github
        golang
        helm
        kubectl
        kubectx
        macos
        minikube
        nmap
        node
        nomad
        npm
        nvm
        pip
        poetry
        terraform
        thefuck
        ufw
        vscode
        web-search
        yarn
        zsh-autosuggestions
        zsh-syntax-highlighting
        )
